### DISCUSSION TITLE
Question: Authorization for clients

### DISCUSSION THREAD

**Discussion by amithshettykdi** [cerbos/cerbos#1036] [Q&A]
By reading the documentation, I see that Cerbos  defines polices which mainly based on role which is great for interactive applications where a user logs in. However in a scenario where a token is issued to a client based on flows like client credentials, we may not have a role associated with the client. We might have some scopes modelled for this. Could you please share your thoughts on how this can be handled?

**Comment by charithe** [comment]
Cerbos supports writing policy rules based on data extracted from a JWT: https://docs.cerbos.dev/cerbos/latest/configuration/auxdata.html. However, we don't automatically populate the principal roles from the JWT because there is no widely accepted standard for that. Therefore you still have to do some mapping in your application to convert the scopes to roles when making the request.

Cerbos is meant to be a backend service used for making authorization decisions and we expect the calling application to handle the identification (authentication) of users. That means that at the time of calling into Cerbos, the application is already aware of the user or application (collectively called a principal in Cerbos terminology) that is trying to perform that action and whatever attributes that principal has. So, in your case your application should extract the necessary information from the token and use that to craft the request to Cerbos.

The `role` is fundamental to how Cerbos operates but it doesn't have to be a literal role. If you don't have any roles in your design, then you can substitute whatever else that makes sense in that context. In your case, it could be the scopes from the token.

**Comment by amithshettykdi** [comment]
Ok. I understand. I have few end points which can be called either by using a token containing a role ( ex: role: "admin") or by a token issued to a client with scope ( scope: "order:read). To model this request I have to pass role or scope in the required field "roles". In the resource policy I should have list of the roles to include scopes.

```
- actions: ['view']
      effect: EFFECT_ALLOW
      roles:
        - admin order:read
      condition:
        match:1
          expr: request.resource.attr.public == true
```

**Comment by charithe** [comment]
OK, that's interesting because it's a bit unusual to have roles for some cases and no roles for some other cases. Typically there's always a role.
To model what you have described, you'll have to do some mapping in your application using the token data. If the token contains a role, then use it as the principal `role` you pass to Cerbos. If the token doesn't contain a role, then use a special virtual role (say, `virt_role`) as the principal's `role`. Then you can write a Cerbos policy like the following. 

```yaml
    # Allow anyone with the admin role to do anything
    - actions: ['*']
      effect: EFFECT_ALLOW
      roles: ["admin"]
     
    
    # If the role is virt_role, then check the JWT for a valid scope before allowing them to view  
    - actions: ["view"]
      effect: EFFECT_ALLOW
      roles: ["virt_role"]
      condition:
        match:
          all:
            of:
              - expr: '"request.resource.attr.public == true'
              - expr: '"order:read" in request.aux_data.jwt.scope'
```
