### DISCUSSION TITLE
TLS error when accessing admin API

### DISCUSSION THREAD

**Discussion by piterfm** [cerbos/cerbos#1096] [Q&A] [answered]
Hi,

I am playing with cerbos locally with the following configuration:

```
---
server:
    httpListenAddr: ':3592'
    grpcListenAddr: ':3593'
    playgroundEnabled: true
    adminAPI:
        adminCredentials:
            passwordHash: JDJ5JDEwJEdEOVFzZDE2VVhoVkR0N2VkUFBVM09nalc0QnNZaC9xc2E4bS9mcUJJcEZXenp5OUpjMi91Cgo=
            username: cerbos
        enabled: true

storage:
    driver: 'disk'
    disk:
        directory: ./src
        watchForChanges: true
```

Running the following command:
```
cerbosctl --username=cerbos --password=cerbosAdmin --server=localhost:3593  get derived_roles
```
gives me the following error:

```
cerbosctl: error: failed to list: error while requesting policies: could not list policies: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"
```

How do I fix this without setting up SSL certs?
