### DISCUSSION TITLE
Are there any condition method "toString"?

### DISCUSSION THREAD

**Discussion by NormandoHall** [cerbos/cerbos#1694] [Q&A] [answered]
Hi all.

I am using conditions to create the `owner` derived role:

```yaml
    - name: owner
      parentRoles: ["auditor", "admin", "superadmin"]
      condition:
        match:
          all:
            of:
              - expr: request.resource.attr.createdBy == request.principal.attr._id
              - expr: request.principal.attr.locked == false
```

But `createdBy` and `_id` are **MongoDB ObjectId**. Are there any method to compare them or cast to string?

Thanks
