### DISCUSSION TITLE
Defining field-level permissions / passing outputs in QueryPlan

### DISCUSSION THREAD

**Discussion by nadavami** [cerbos/cerbos#2049] [Q&A]
First off, thanks for an awesome product!

We are currently using Cerbos and the Cerbos mongoose orm adapter to create auth rules that filter our database. Is it possible to define rules in cerbos that only allow updates to certain database fields. 

For example we would love to be able to do something like: 
```yaml
    - actions: ['create', 'find', 'update']
      effect: EFFECT_ALLOW
      roles: ['Admin']

    - actions: ['find', 'update']
      effect: EFFECT_ALLOW
      roles: ['User']
      condition:
        match:
          expr: P.id == R.id
     allowedFields: ['language']
```

We would manage what to do with allowedFields in our backend, but it would be very useful to be able to define extra metadata in cerbos and have it passed through. "Outputs" comes close to this, but they aren't available in the QueryPlan output and we would like to avoid making two multiple requests to cerbos if we can avoid it.

**Comment by charithe** [comment]
Hi. I am trying to understand your use case a bit better. Is it correct to say that you want to figure out the field on which `find` or `update` is being done? If so, one way to achieve that would be through prefixing your actions (e.g. `language:find`). Cerbos supports wildcards so the following rule would still work the same as above.   

```yaml
    - actions: ['*:find', '*:update']
      effect: EFFECT_ALLOW
      roles: ['User']
      condition:
        match:
          expr: P.id == R.id
```

**Reply by nadavami** [reply]
It would be the other way around for our use-case. We would like to use cerbos to define more fine grain rules which determine the fields that the principal is ultimately allowed to read or update. 

So where P.id == R.id would filter out the relevant documents, something like allowedFields would allow us to use cerbos to define which fields in the documents we want to allow the user to update (or see). 

So if our document was something like:
```js
{ id: 123, language: "en", email: "abc@example.com", internal_value: "xyz" }
```

We could allow the a "User" role to read/update: ["language", "email"] but allow an admin to read/update: ["language", "email", "internal_value"].

**Reply by charithe** [reply]
Can't they be stored as variables? For example:

```yaml
# user_variables.yaml
apiVersion: api.cerbos.dev/v1
exportVariables:
  name: common_variables
  definitions:
    allowedFields: '["language", "email"]'
```

```yaml
# foo.yaml
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: default
  resource: foo
  variables:
    import:
      - common_variables
  rules:
    - actions: ['create', 'find', 'update']
      effect: EFFECT_ALLOW
      roles: ['Admin']

    - actions: ['find', 'update']
      effect: EFFECT_ALLOW
      roles: ['User']
      condition:
        match:
          all:
            of:
              - expr: P.id == R.id
              - expr: R.attr.field in V.allowedFields
```
