### DISCUSSION TITLE
Multiple admin API credentials

### DISCUSSION THREAD

**Discussion by G-Salviati** [cerbos/cerbos#2537] [Q&A] [answered]
Hello,
is there any way to declare more than one admin API user? 

I'm using helm and the server configuration in the values.yaml
```
cerbos:
  config:
    server:
      adminAPI:
        enabled: true
        adminCredentials:
          username: ${ADMIN_API_USERNAME}
          passwordHash: ${ADMIN_API_PASSWORD_HASH}

envFrom:
  - secretRef:
      name: cerbos-sensitive

```

I would like to have one more admin API user. Is it possible?
