### DISCUSSION TITLE
Test fixtures

### DISCUSSION THREAD

**Discussion by dbuduev** [cerbos/cerbos#285] [Ideas]
## Motivation
Policy tests can have better UX. Right now, every test case requires defining the whole request in full. Instead, we should allow parts (or the whole) of the request to be defined only once.

## Proposal
The examples below use HR platform playground data

### Option 1:  add YAML anchors to existing tests
Add top-level `principals` and `resources` keys to tests:
<details>
<p>

```yaml
name: HR platform TestSuite
description: Testing Harry leave request
principals:
  - &harry
    id: harry
    roles:
      - employee
    attr:
      department: marketing
      geography: GB
      team: design
  - &maggie
    id: maggie
    roles:
      - employee
      - manager
    attr:
      department: marketing
      geography: GB
      managed_geographies:
        - GB
        - US
      team: design
resources:
  - &draft_leave_request
    id: xx125
    kind: leave_request
    policyVersion: default
    attr:
      department: marketing
      geography: GB
      id: XX125
      owner: harry
      status: DRAFT
      team: design
  - &pending_leave_request
    id: xx125
    kind: leave_request
    policyVersion: default
    attr:
      department: marketing
      geography: GB
      id: XX125
      owner: harry
      status: PENDING_APPROVAL
      team: design
tests:
  - name: Harry drafts a leave request
    input:
      actions: [ "create", "view", "approve" ]
      principal: *harry
      resource: *draft_leave_request
    expected:
      create: EFFECT_ALLOW
      view: EFFECT_ALLOW
      approve: EFFECT_DENY
  - name: Maggie and Harry's draft leave request
    input:
      actions: [ "create", "view", "approve" ]
      principal: *maggie
      resource: *draft_leave_request
    expected:
      create: EFFECT_DENY
      view: EFFECT_DENY
      approve: EFFECT_DENY
  - name: Harry and his pending leave request
    input:
      actions: [ "create", "view", "approve" ]
      principal: *harry
      resource: *pending_leave_request
    expected:
      create: EFFECT_ALLOW
      view: EFFECT_ALLOW
      approve: EFFECT_DENY
  - name: Maggie and Harry's pending leave request
    input:
      actions: [ "create", "view", "approve" ]
      principal: *maggie
      resource: *pending_leave_request
    expected:
      create: EFFECT_DENY
      view: EFFECT_ALLOW
      approve: EFFECT_ALLOW
```

</p>
</details>

Pros: 
- Very easy to implement (consider it done).
- Follow an existing tests pattern.

Cons:
- YAML anchors is an "advanced" YAML feature, so users might not understand the syntax. IMO, it's quite easy to follow it provided there's an example.
- It is not possible to share data between test suites.

### Option 2: Test fixture keeps principals and resources in external YAML files (in a given directory)
This option introduces a test fixture as a set of files in a given directory. The test fixture directory contains three kinds of YAML files:
1. `principals.yml` containing a list of principals.
```yaml
- 
    id: harry
    roles:
      - employee
    attr:
      department: marketing
      geography: GB
      team: design
-
    id: maggie
    roles:
      - employee
      - manager
    attr:
      department: marketing
      geography: GB
      managed_geographies:
        - GB
        - US
      team: design

```
1. `resources.yml` containing a list of resources.
1. tests YAML files
```yaml
tests:
  - name: Harry drafts a leave request
    input:
      actions: [ "create", "view", "approve" ]
      principal: harry
      resource: draft_leave_request
    expected:
      create: EFFECT_ALLOW
      view: EFFECT_ALLOW
      approve: EFFECT_DENY
```

Pros:
- Easy to implement.
- A user can re-use data between tests.

Cons:
- There's syntax overheads in particular for declaring expected outcomes.

### Option 3: Test fixture for table-driven tests
The following example uses Markdown format, but we can also use CSV.

This option introduces a test fixture as a set of files in a given directory. The test fixture directory contains three kinds of CSV files:
1. `principals.csv` - A parser must understand a handful of predefined root-level principal properties like `id`, `roles`; everything else can fall into attributes mapping during the parsing phase.

| id | roles | department | geography | team | managed_geography |
| -- | -- | -- | -- | -- | -- |
| maggie | employee, manager | marketing | GB | design | GB, US |
| harry | employee | marketing | GB | design |  |
2. `resources.csv` - `id`, `kind`, `policyVersion` are predefined properties. Everything else belongs to `attr` mapping.
3. `harry_test.csv` - can be any number of tests files having `_test.csv` suffix.

| principal | resource | action | expected |
| -------- | -------- | -------- | -------- |
|  harry | draft_leave_request | create |  allow |
|  harry | draft_leave_request | view |  allow |
|  harry | draft_leave_request | approve |  deny |
|  maggie | draft_leave_request | create |  deny |
|  maggie | draft_leave_request | view |  deny |
|  maggie | draft_leave_request | approve |  deny |
|  maggie | pending_leave_request | create |  deny |
|  maggie | pending_leave_request | view |  allow |
|  maggie | pending_leave_request | approve |  allow |

Pros:
- Minimum syntax overhead.
- CSVs are simple to understand and easy to author for non-technical users
  - A user can use spreadsheets like Microsoft Excel to author tests.
- Easy to include in reports.

Cons:
- A bit more work to implement than other options, but still straightforward.

**Comment by charithe** [comment]
All three are good options. However, as noted, YAML anchors are only usable within a single file so that option does not provide a lot of flexibility for reuse. CSV while simple will be a pain to implement because there are lots of edge cases around parsing CSV. The most obvious being that it's not a typed format so we'll have to guess the data types of attributes. It is also not going to be easy to define attributes that are lists or maps (specially when they are nested).  That leaves option 2 as the best one IMO.

One thing that might need a bit more thought about is the level of granularity for defining the test data. Is it just going to be at the level of principals and resources? Is it possible to share attributes between principal/resource definitions with maybe just one or two being overridden (YAML anchors can do this IIRC so that might be an option).

How about emulating table-driven tests by letting users define a list of principals or resources in a single test so that the framework can work through all the combinations automatically?. For example:

```yaml
tests:
  - name: Test access to draft leave request
    input:
      actions: [ "create", "view", "approve" ]
      principals: [harry, maggie]
      resource: draft_leave_request
    expected:
      harry:
        create: EFFECT_ALLOW
        view: EFFECT_ALLOW
        approve: EFFECT_DENY
      maggie:
        create: EFFECT_DENY
        view: EFFECT_DENY
        approve: EFFECT_DENY
```

**Reply by dbuduev** [reply]
> One thing that might need a bit more thought about is the level of granularity for defining the test data. Is it just going to be at the level of principals and resources? Is it possible to share attributes between principal/resource definitions with maybe just one or two being overridden (YAML anchors can do this IIRC so that might be an option).

Yes, YAML anchors and [Merge Keys](https://yaml.org/type/merge.html)

Emulating table-driven in YAML looks good. I'd suggest a variation though. Since actions are presented in an array (so the order is defined), present effects in an array as well.
```yaml
tests:
  - name: Test access to draft leave request
    input:
      actions: [ "create", "view", "approve" ]
      principals: [harry, maggie]
      resource: draft_leave_request
    expected:
      harry: ["allow", "deny", "deny"]
      maggie: ["deny", "allow", "deny"]
```
What do you think?

**Reply by dbuduev** [reply]
or even excluding `input.principals`:
```yaml
tests:
  - name: Test access to draft leave request
    input:
      actions: [ "create", "view", "approve" ]
      resource: draft_leave_request
    expected:
      harry: ["allow", "deny", "deny"]
      maggie: ["deny", "allow", "deny"]
```
