### ISSUE TITLE
Inconsistent operator names in Query Plan

### ISSUE THREAD

**Issue by alexolivier** [cerbos/cerbos#1014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Depending on how conditions are defined, the `operator` in a `PlanResources` response is either `and` or `_&&_`, `or` or `_||_` etc

### Expected Behavior

These should be consistent

### Steps To Reproduce

https://play.cerbos.dev/p/l4Y2oIiAP61eea3c0meOfWIEay2Wje99

When using alIOf
```
      condition:
        match:
          all:
            of:
              - expr: request.resource.attr.status == "DRAFT"
              - expr: request.resource.attr.test == "meh"
```
you get the expected

```
 "filter": {
    "kind": "KIND_CONDITIONAL",
    "condition": {
      "expression": {
        "operator": "and",
        "operands": [
...
```

but when using inline conditionals eg

```
      condition:
        match:
          expr: request.resource.attr.status == "DRAFT" && request.resource.attr.test == "meh"
```
you get

```  "filter": {
    "kind": "KIND_CONDITIONAL",
    "condition": {
      "expression": {
        "operator": "_&&_",
        "operands": [
```

### Environment

```markdown
- Cerbos version: v0.18.0
```
