### ISSUE TITLE
Traces can be exported via OTLP

### ISSUE THREAD

**Issue by rcrowe** [cerbos/cerbos#1018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Be able to configure trace exporting to except [OTLP](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md) as an export mechanism.

### What would the ideal solution look like to you?

```
tracing:
  sampleProbability: 0.5
  exporter: otlp
  otlp:
    collectorEndpoint: "otel:4317"
```
