### ISSUE TITLE
Non-existent attribute access causes an expression to short-circuit

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#1055]
Consider the following case:

```yaml
match:
  any:
    of:
      - expr: request.principal.attr.missing_attr == "foo" 
      - expr: request.principal.attr.other_attr == "bar"
```

If `missing_attr` is not defined in the principal, the whole expression block returns `false` even if `other_attr` is equal to `bar`.
