### ISSUE TITLE
Resource planner API returns an impossible membership test

### ISSUE THREAD

**Issue by dbuduev** [cerbos/cerbos#1058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The produced AST contains an expression that should be evaluated in Cerbos
```yaml
      - expression:
          operator: in
          operands:
          - variable: request.resource.attr.accountId
          - value: []
```

### Expected Behavior

An impossible membership test expression should be replaced with the value `false`.
