### ISSUE TITLE
Allow `time.Now()` to be overriden during policy tests

### ISSUE THREAD

**Issue by rcrowe** [cerbos/cerbos#1167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Cerbos allows [timestamp conditions](https://docs.cerbos.dev/cerbos/latest/policies/conditions.html#_timestamps) as part of the rules in a Policy, which can not currently be tested deterministically because [time.Now](https://github.com/cerbos/cerbos/blob/33fccbfce60d077ee633a75294f218fba80399d6/internal/conditions/cerbos_lib.go#L156) is used.

[Testing policies](https://docs.cerbos.dev/cerbos/latest/policies/compile.html#_testing_policies) should allow the ability to override the time so that rule tests can be deterministically tested. Take the example `timestamp(P.attr.some_claim).timeSince() < duration("1h")` a passing test will fail after 1hr.

I'm assuming for now that this is dictated by https://github.com/cerbos/cerbos/blob/33fccbfce60d077ee633a75294f218fba80399d6/internal/conditions/cerbos_lib.go#L156

### What would the ideal solution look like to you?

Be able to provide a specific timestamp to execute the test with, here I've supplied **now** as an RFC 3339 string.

```yaml
tests:
  - name: Check access was granted in the last hour
    now: "2022-08-15T14:49:03+00:00"
    input:
      principals:
        - some-principal
      resources:
        - some-resource
      actions:
        - some-action
    expected:
```
