### ISSUE TITLE
Incorrect query plan

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#1214]
Given the policy definitions below, the query planner produces an incorrect plan for a principal with `package: PREMIUM`.

The produced plan is `(or (not (in "PRO" request.resource.attr.tags)) (in "PRO" request.resource.attr.tags))`. It should be just `(not (in "PRO" request.resource.attr.tags))`.

Resource

```yaml
---
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  importDerivedRoles:
    - tiers
  resource: NEWS
  version: default
  rules:
  - actions: [ "SHOW" ]
    derivedRoles:
      - gold
    condition:
      match:
        expr: |-
            !("PRO" in R.attr.tags)
    effect: EFFECT_ALLOW

  - actions: [ "SHOW" ]
    derivedRoles:
      - platinum
    condition:
      match:
        expr: |-
            ("PRO" in R.attr.tags)
    effect: EFFECT_ALLOW
```

Derived Roles

```yaml
---
apiVersion: "api.cerbos.dev/v1"
derivedRoles:
  name: tiers
  definitions:
    - name: gold
      parentRoles:
        - user
      condition:
        match:
          any:
            of:
              - expr: request.principal.attr.package == "PRO"
              - expr: request.principal.attr.package == "PREMIUM"
              - expr: request.principal.attr.package == "PREMIUM_PLUS"

    - name: platinum
      parentRoles:
        - user
      condition:
        match:
          any:
            of:
              - expr: request.principal.attr.package == "PREMIUM_XTRA"
              - expr: request.principal.attr.package == "PREMIUM_PLUS"
```

Request 

```
cat <<EOF | curl --silent "localhost:3592/api/plan/resources?pretty" -d @-
{
  "requestId":  "test01", 
  "action":  "SHOW", 
  "resource":  { 
    "kind":  "NEWS"
  },
  "principal":  {
    "id":  "alicia", 
    "roles":  ["user"], 
    "attr": { 
      "package": "PREMIUM"
    }
  },
  "includeMeta": true
}
EOF
```
