### ISSUE TITLE
Query plan fails on nested comprehensions

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#1276]
**Error**

```
expect expression, got *enginev1.PlanResourcesFilter_Expression_Operand_Variable
```

**Policy**

```yaml
---
apiVersion: "api.cerbos.dev/v1"
resourcePolicy:
  version: "default"
  resource: "report_with_map"
  rules:
    - actions:
        - write
      effect: EFFECT_ALLOW
      roles:
        - USER
      condition:
        match:
          expr: hasIntersection(R.attr.workspaces, P.attr.workspaces.filter(w, w.role=="MANAGER").map(w, w.name))
```

**Request**

```
cat <<EOF | curl -k --silent "https://localhost:3592/api/plan/resources?pretty" -d @-
{
    "requestId": "test01",
    "action": "write",
    "resource": {
        "policyVersion": "default",
        "kind": "report_with_map"
    },
    "principal": {
        "id": "123",
        "roles": [
            "USER"
        ],
        "attr": {
            "workspaces": [
                {
                    "name": "workspaceA",
                    "role": "MANAGER"
                },
                {
                    "name": "workspaceB",
                    "role": "MEMBER"
                }
            ]
        }
    }
}
EOF
```
