### ISSUE TITLE
Plan Resource returns NO_MATCH for derived roles

### ISSUE THREAD

**Issue by anorneto** [cerbos/cerbos#1300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I define a derivedRole in a Resource Policy the PlanResources API always returns NO_MATCH. If I change it to a role it works as expected.

### Expected Behavior

If I change the resource policy to _roles_ instead of _derivedRoles_ it works as expected :

```json
{
	"action": "read",
	"resourceKind": "asset",
	"filter": {
		"kind": "KIND_CONDITIONAL",
		"condition": {
			"expression": {
				"operator": "or",
				"operands": [
					{
						"expression": {
							"operator": "in",
							"operands": [
								{
									"variable": "request.resource.id"
								},
								{
									"value": [
										"Asset 01"
									]
								}
							]
						}
					},
					{
						"expression": {
							"operator": "in",
							"operands": [
								{
									"variable": "request.resource.attr.asset_name"
								},
								{
									"value": [
										"Asset 01"
									]
								}
							]
						}
					}
				]
			}
		}
	},
	"meta": {
		"filterDebug": "(or (in request.resource.id [\"Asset 01\"]) (in request.resource.attr.asset_name [\"Asset 01\"]))"
	}
}
```

### Steps To Reproduce

**my derived roles definition**
```yaml
apiVersion: "api.cerbos.dev/v1"
derivedRoles:
  name: derived_roles_common
  definitions:
    - name: superuser
      parentRoles:
        - superuser

    - name: admin
      parentRoles:
        - admin

    - name: tester
      parentRoles:
        - dev
        - qa

    - name: reader
      parentRoles:
        - reader
        - viewer
```

**resource policy**
```yaml
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: "asset"
  importDerivedRoles:
    - derived_roles_common
  rules:
    - actions: ["*"]
      effect: EFFECT_ALLOW
      roles:
        - admin

    - actions: ["read"]
      effect: EFFECT_ALLOW
      derivedRoles:
        - reader
      condition:
        match:
          any:
            of:
              - expr: P.attr.allowed_assets == 'ALL'
              - expr: R.id in P.attr.allowed_assets
              - expr: R.attr.asset_name in P.attr.allowed_assets
```

**/api/plan/resources body**
```json

{
  "action": "read",
  "principal": {
    "id": "user_id",
    "roles": [
      "reader"
    ],
    "attr": {
			"allowed_assets": ["Asset 01"]
    }
  },
  "resource": {
    "kind": "asset",
    "attr": {}
  },
  "includeMeta": true
}
```

**/api/plan/resources Response**

```json
{
	"action": "read",
	"resourceKind": "asset",
	"filter": {
		"kind": "KIND_ALWAYS_DENIED"
	},
	"meta": {
		"filterDebug": "NO_MATCH"
	}
}
```

### Environment

```markdown
- OS: MacOs 12.2.1
- Cerbos version: 0.21.0
- Docker version:
- Go version:
```
