### ISSUE TITLE
Invalid expressions are silently ignored by the planner

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#1333]
Policy:

```yaml
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  resource: top
  version: default
  rules:
    - actions:
        - VIEW
      roles:
        - customer-user
      condition:
        match:
          any:
            of:
              - expr: R.attr.custAnal in P.attr.custAllowedValues
              - expr: R.attr.salhAnal in P.attr.salhAllowedValues
      effect: EFFECT_ALLOW
```

Request:

```sh
cat <<EOF | curl --silent "http://localhost:3592/api/plan/resources?pretty" -d @-
{
  "requestId": "query-plan",
  "resource": {
    "kind": "top"
  },
  "principal": {
    "id": "123",
    "roles": [
      "customer-user"
    ],
    "attr": {
      "custAllowedValues": "VALUE1",
      "salhAllowedValues": "VALUE2"
    }
  },
  "action": "VIEW",
  "includeMeta": true
}
EOF
```

This produces an `ALWAYS_ALLOWED` query plan instead of `CONDITIONAL` as it should. The reason is that the principal attributes in the request are strings instead of lists. The policy condition uses the `in` operator and because strings are not supported by `in`, the planner is silently ignoring those invalid expressions.

The following request with the right data types works as expected.

```sh
cat <<EOF | curl --silent "http://localhost:3592/api/plan/resources?pretty" -d @-
{
  "requestId": "query-plan",
  "resource": {
    "kind": "top"
  },
  "principal": {
    "id": "123",
    "roles": [
      "customer-user"
    ],
    "attr": {
      "custAllowedValues": ["VALUE1"],
      "salhAllowedValues": ["VALUE2"]
    }
  },
  "action": "VIEW",
  "includeMeta": true
}
EOF
```
