### ISSUE TITLE
Make resource policies optional for resources targeted by principal policies 

### ISSUE THREAD

**Issue by oguzhand95** [cerbos/cerbos#1397]
If there is a principal policy defined that is targeting `dummy_resource` as follows;

```yaml
apiVersion: api.cerbos.dev/v1
principalPolicy:
  version: default
  principal: some_principal
  rules:
    - resource: dummy_resource
      actions:
        - action: read
          effect: EFFECT_ALLOW
```
and there is no resource policy defined for the `dummy_resource` we have an unexpected outcome depending on the actions passed to the `checkResources` API.

When the value of the `actions` in the request only consists `read`, we get `EFFECT_ALLOW`.

When the value of the `actions` in the request consists of `read` and any other action(s), we get `EFFECT_DENY` for both while we must get `EFFECT_ALLOW` for the `read` action.

This can be solved by having an empty resource like this;
```yaml
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: default
  resource: dummy_resource
```
