### ISSUE TITLE
Grouping test results by principal does not update the tally

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#1403]
Consider the following test suite definition:

```yaml
---
name: Foo
resources:
  my_resource_1:
    id: my_resource_1
    kind: my_resource
principals:
  some_user:
    id: some_user
    roles: ["test"]
  admin_user:
    id: admin_user
    roles: ["admin"]
tests:
  - name: Test1
    input:
      principals:
        - some_user
        - admin_user_1
      resources:
        - my_resource_1
      actions:
        - create
    expected:
      - principal: some_user
        resource: my_resource_1
        actions:
          create: EFFECT_DENY

  - name: Test2
    input:
      principals:
        - admin_user
      resources:
        - my_resource_1
      actions:
        - create
    expected:
      - principal: admin_user
        resource: my_resource_1
        actions:
          create: EFFECT_ALLOW
```

The output of this test looks like the following:

```
Test results
└─┬Foo (x_test.yaml) [2 OK] [1 FAILED]
  ├─┬some_user
  │ └─┬my_resource_1
  │   └──create [OK]
  └─┬admin_user
    └─┬my_resource_1
      └──create [OK]

3 tests executed [2 OK] [1 FAILED]
```

`Test1` creates an **implicit** test case for `admin_user` for `create` action with the expectation of `EFFECT_DENY` because it is listed in `principals` but has no corresponding `expected` entry. However `Test2` is an **explicit** test case for the same principal and action but with the expectation of `EFFECT_ALLOW`.

When the test suite is run, the implicit test fails because the expectation of `EFFECT_DENY` does not match the actual effect of `EFFECT_ALLOW`. Then the explicit test (`Test2`) is run and succeeds because the expectation matches the actual result. Because we group the results by principal and action, this result overwrites the previous failure entry. However, the running tally is not updated to reflect that fact and we end up with the rather confusing `3 tests executed [2 OK] [1 FAILED]` message.

There are a couple ways in which we could handle this:
1. Warn the users when they have conflicting `principal:action` tests
1. Group the test results by test name first (we may still need to detect duplicate test names)
1. Instead of keeping a running tally, do the tally at the end

My personal preference is for grouping by test name first because that would produce the least surprising/confusing output for users.
