### ISSUE TITLE
Reject duplicate tests

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#1410]
Follows from #1403 

In the following test definition, `Test1` generates an implicit test case for `admin_user` because it is listed as a principal. `Test2` is an explicitly defined test case for the same principal, resource and action. We should detect this scenario and prompt the user to fix it (either remove `admin_user` from the `principals` list of `Test1` OR delete `Test2`)

```yaml
---
name: Foo
resources:
  my_resource_1:
    id: my_resource_1
    kind: my_resource
principals:
  some_user:
    id: some_user
    roles: ["test"]
  admin_user:
    id: admin_user
    roles: ["admin"]
tests:
  - name: Test1
    input:
      principals:
        - some_user
        - admin_user
      resources:
        - my_resource_1
      actions:
        - create
    expected:
      - principal: some_user
        resource: my_resource_1
        actions:
          create: EFFECT_DENY

  - name: Test2
    input:
      principals:
        - admin_user
      resources:
        - my_resource_1
      actions:
        - create
    expected:
      - principal: admin_user
        resource: my_resource_1
        actions:
          create: EFFECT_ALLOW
```
