### ISSUE TITLE
Cerbos compile failed

### ISSUE THREAD

**Issue by mohamadnosratian** [cerbos/cerbos#1414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error :

Missing Imports
resource_channel.yaml: Import 'user_access' not found

Load failures
role_user_access.yaml: failed to unmarshal JSON: proto: syntax error (line 1:486): unexpected token [

cerbos: error: failed to compile

### Expected Behavior

Expected to compile without any error

### Steps To Reproduce

* config:
``` YAML
---
server:
  httpListenAddr: ":3592"
storage:
  driver: "disk"
  disk:
    directory: "./tutorial/policies"
```
* policies:
`role_user_access.yaml`
``` YAML
---
apiVersion: api.cerbos.dev/v1
description: |-
  Only accessed by author, admin or owner of the resource
derivedRoles:
  name: user_access
  definitions:
    - name: access
      parentRoles: ["user"]
      condition:
        match:
          any:
            of:
              - expr: request.resource.attr.ownerId == request.principal.id
              - expr: request.principal.id in request.resource.attr.authorIds

    - name: visible
      parentRoles: ["user"]
      condition:
        match:
          any:
            of:
              - expr: request.resource.attr.visibility == "PUBLIC"
              - expr: request.resource.attr.payed == true

    - name: private
      parentRoles: ["user"]
      condition:
        match:
          - expr: request.resource.attr.visibility == "PRIVATE"
``` 
`resource_user.yaml`
``` YAML
---
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: "user"
  rules:
    - actions:
        - create
      effect: EFFECT_ALLOW
      roles:
        - user
    - actions:
        - update
        - read
      effect: EFFECT_ALLOW
      roles:
        - user
      condition:
        match:
          expr: request.resource.id == request.principal.id
    - actions:
        - "*"
      effect: EFFECT_ALLOW
      roles:
        - admin

```
`resource_channel.yaml`
``` YAML
---
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  importDerivedRoles:
    - user_access
  resource: "channel"
  rules:
    - actions:
        - create
        - update
        - delete
        - read
      effect: EFFECT_ALLOW
      derivedRoles:
        - access
    - actions:
        - read
      effect: EFFECT_ALLOW
      derivedRoles:
        - visible
    - actions:
        - "*"
      effect: EFFECT_ALLOW
      roles:
        - admin
    - actions:
        - "*"
      effect: EFFECT_DENY
      derivedRoles:
        - private

```

* compile command:
``` sh
docker run --rm --name cerbos -t \
  -v "$(pwd)/tutorial:/tutorial" \
  ghcr.io/cerbos/cerbos:latest compile "./tutorial/policies"
```

### Environment

```markdown
- OS: Windows 11
- Cerbos version: 0.23.1
- Docker version: 4.15.0
- Go version: go1.19.3
```
