### ISSUE TITLE
Document how to use Cerbos as a service container on GitHub actions

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#1443]
It should be possible to start Cerbos as a service container on GitHub Actions and use it for tests. 

- Because services are started before checking out the source, Cerbos will have to start with a SQLite in-mem database as the store. 
- In the workflow, use `cerbos-setup-action` to install `cerbosctl`
- Add another workflow step to use `cerbosctl put` to load policies and schemas from a given directory

**Comment by oguzhand95** [comment]
I have done a bit of reading on this and actually tried a couple of things on a dummy repository.

Unfortunately, it is not possible to set arguments to the service as of now ([source](https://github.com/actions/runner/discussions/1872)).  Since it is not possible, the *service container* cannot be configured the way we want.

> Because services are started before checking out the source, Cerbos will have to start with an SQLite in-mem database as the store.

I've checked this in case something changed during the time but unfortunately, I did not find anything.

I think one possible solution would be to release an extra image with an image tag like `ghcr.io/cerbos/cerbos:0.26.0-ci` where we have a default configuration like this;
```yaml
audit:
  accessLogsEnabled: true
  backend: file
  decisionLogsEnabled: true
  enabled: true
  file:
    path: stdout

engine:
  defaultPolicyVersion: default

server:
  adminAPI:
    adminCredentials:
      passwordHash: JDJ5JDEwJEdEOVFzZDE2VVhoVkR0N2VkUFBVM09nalc0QnNZaC9xc2E4bS9mcUJJcEZXenp5OUpjMi91Cgo= # cerbosAdmin
      username: cerbos
    enabled: true
    grpcListenAddr: ":3593"
    httpListenAddr: ":3592"

storage:
  driver: sqlite3
  sqlite3:
    dsn: ":memory:?_fk=true"

telemetry:
  disabled: true
```

Then, we could ask the users to use this image if cerbos is needed to run as a *container service* in a GitHub Workflow.
