### ISSUE TITLE
ResourcePolicy wildcard on resource

### ISSUE THREAD

**Issue by famz** [cerbos/cerbos#1527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

It seems all resource policies are specific to one resource, ie no wildcard support in resourcePolicy.resource.

So although in this example from the tutorial, there is a delimiter in the resource name, it cannot apply real hierarchy in the resource definitions.

```
---
apiVersion: api.cerbos.dev/v1
variables: 
  is_corporate_network: |-
    P.attr.ip_address.inIPAddrRange("10.20.0.0/16")
resourcePolicy:
  version: "default" 
  scope: "acme.corp" 
  importDerivedRoles:
    - apatr_common_roles 
  resource: "album:object"      <------------
  rules:
    - actions: ['*'] 
      effect: EFFECT_ALLOW
      derivedRoles:
        - owner 
```

For example, it is not possible to do `resource: "album:*"`.

What I'm having in mind is to have both: `resource: "s3:bucket:*"` & `resource: "s3:bucket:MyPublicDataBucket"` and define both general and specific policies (such as anonymous access):

```
---
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: "s3:bucket:*"  
  rules:
    - actions: ['*'] 
      effect: EFFECT_ALLOW
      roles:
        - admin
---
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: "s3:bucket:MyPublicDataBucket"  
  rules:
    - actions: ['*'] 
      effect: EFFECT_ALLOW
      roles:
        - anonymous
```
