### ISSUE TITLE
Add LoadBalancer service type support for Static IP

### ISSUE THREAD

**Issue by roman-supy-io** [cerbos/cerbos#1604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

`LoadBalancer` k8s service type can be configured with static pre-created ip.
Right now, it's impossible to do OOB without downloading/modifying the existing chart.

### What would the ideal solution look like to you?

To be able to specify static ip address in `values.yaml`:

```yaml
# Cerbos service settings.
        service:
          type: LoadBalancer
          httpPort: 3592
          grpcPort: 3593
          httpNodePort: 13592
          grpcNodePort: 13593
        + loadBalancerIP: "10.0.4.1"
```

**Comment by charithe** [comment]
We can add that to the chart and it will be available in the next release. In the meantime though, you can use a Helm post-renderer to change the manifest without locally modifying the chart.

Create `kustomization.yaml`:

```yaml
---
resources:
  - service-base.yaml
patches:
  - patch: |-
      - op: add
        path: /spec/loadBalancerIP
        value: 10.0.0.10
    target:
      version: v1
      kind: Service
```

Create `kustomize.sh`:

```shell
#!/usr/bin/env bash

cat > service-base.yaml
exec kubectl kustomize
```

Now you can run Helm pointing to this script:

```sh
helm template cerbos/cerbos --post-renderer ./kustomize.sh
```
