### ISSUE TITLE
PlanResources internal error

### ISSUE THREAD

**Issue by ctrworthin** [cerbos/cerbos#1719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Calling PlanResources from Ruby SDK client:

```ruby
res = {kind: "con:person"}
principal = {id: "user", roles: ["user"], attributes: {account_id: "123"}}
resp = cerb.plan_resources(principal: principal, resource: res, action: 'index', include_metadata: true)
```

Relevant policy snippet:

```yaml
# ... 
    - roles: ["user"]
      actions:
        - index
      effect: EFFECT_ALLOW
      condition:
        match:
          expr: P.attr.account_id in (R.attr.accounts_people.map(ap, ap.account_id))
```

Results in an exception and the following logs from cerbos:

```json
{
  "log.logger": "cerbos.audit",
  "log.kind": "decision",
  "callId": "01H6Q6D5X7SQEC7CFYC669583C",
  "timestamp": "2023-08-01T00:01:46.458123843Z",
  "peer": {
    "address": "172.28.0.1:63242",
    "userAgent": "cerbos-sdk-ruby/0.7.0 grpc-ruby/1.56.2 grpc-c/33.0.0 (osx; chttp2)"
  },
  "planResources": {
    "input": {
      "requestId": "4dd55853-3913-432f-8729-84c895042de9",
      "action": "index",
      "principal": {
        "id": "user",
        "roles": [
          "user"
        ],
        "attr": {
          "account_id": "123"
        }
      },
      "resource": {
        "kind": "con:person"
      },
      "includeMeta": true
    },
    "error": "expected expression, got *enginev1.PlanResourcesFilter_Expression_Operand_Variable"
  }
}
{
  "log.level": "error",
  "@timestamp": "2023-08-01T00:01:46.460Z",
  "log.logger": "cerbos.grpc",
  "message": "Resources query plan request failed",
  "grpc.start_time": "2023-08-01T00:01:46Z",
  "system": "grpc",
  "span.kind": "server",
  "grpc.service": "cerbos.svc.v1.CerbosService",
  "grpc.method": "PlanResources",
  "peer.address": "172.28.0.1:63242",
  "grpc.request.meta": {
    "request_id": "4dd55853-3913-432f-8729-84c895042de9"
  },
  "cerbos": {
    "call_id": "01H6Q6D5X7SQEC7CFYC669583C"
  },
  "error": "expected expression, got *enginev1.PlanResourcesFilter_Expression_Operand_Variable"
}
{
  "log.logger": "cerbos.audit",
  "log.kind": "access",
  "callId": "01H6Q6D5X7SQEC7CFYC669583C",
  "timestamp": "2023-08-01T00:01:46.407682593Z",
  "peer": {
    "address": "172.28.0.1:63242",
    "userAgent": "cerbos-sdk-ruby/0.7.0 grpc-ruby/1.56.2 grpc-c/33.0.0 (osx; chttp2)"
  },
  "method": "/cerbos.svc.v1.CerbosService/PlanResources",
  "statusCode": 13
}
{
  "log.level": "error",
  "@timestamp": "2023-08-01T00:01:46.461Z",
  "log.logger": "cerbos.grpc",
  "message": "Handled request",
  "grpc.start_time": "2023-08-01T00:01:46Z",
  "system": "grpc",
  "span.kind": "server",
  "grpc.service": "cerbos.svc.v1.CerbosService",
  "grpc.method": "PlanResources",
  "grpc.request.meta": {
    "request_id": "4dd55853-3913-432f-8729-84c895042de9"
  },
  "cerbos": {
    "call_id": "01H6Q6D5X7SQEC7CFYC669583C"
  },
  "peer.address": "172.28.0.1:63242",
  "error": "rpc error: code = Internal desc = Resources query plan request failed",
  "grpc.code": "Internal",
  "grpc.time_ms": 58.785
}
```

### Expected Behavior

Expected to receive a `Cerbos::Output::PlanResource` response without errors / exceptions.

### Steps To Reproduce

See 'current behavior'.

Suspect, but not confirmed, the client language / sdk (Ruby) are irrelevant, as the error appears to happen server side, within Cerbos.

### Environment

```markdown
- OS: OSX 13.2.1
- Cerbos version: Confirmed on 0.28.0, 0.29.0
- Docker version: Docker Desktop (4.6.0 (75818))
- Go version: N/A (ruby client SDK)
```

### Anything else?

Removing the 'condition' from the policy, everything executes as expected. Policy file passes validation. I suspect it is something about the expression, but if there is something wrong with how it is written, I would have expected the validator to flag it.

**Comment by dbuduev** [comment]
I presume the expected output is:

```yaml
      kind: KIND_CONDITIONAL
      condition:
        expression:
          operator: in
          operands:
            - value: "123"
            - expression:
                operator: map
                operands:
                  - variable: request.resource.attr.accounts_people
                  - expression:
                      operator: lambda
                      operands:
                        - variable: ap.account_id
                        - variable: ap
```
