### ISSUE TITLE
Variables referencing variables produce nondeterministic output

### ISSUE THREAD

**Issue by haines** [cerbos/cerbos#1746]
https://play.cerbos.dev/p/1Jx64d611fcEQnzV6OBENU77GA1vKzm3

We store variables in a map, so the order in which they are defined is nondeterministic. Unfortunately, when they are evaluated this seems to result in nondeterministic output if a variable references another variable.

In the playground above, we have the following simple policy:

```yaml
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: default
  resource: example_resource

  variables:
    local:
      one: V.two
      two: V.three
      three: "true"

  rules:
    - actions:
        - one
      effect: EFFECT_ALLOW
      roles:
        - USER
      condition:
        match:
          expr: V.one

    - actions:
        - two
      effect: EFFECT_ALLOW
      roles:
        - USER
      condition:
        match:
          expr: V.two

    - actions:
        - three
      effect: EFFECT_ALLOW
      roles:
        - USER
      condition:
        match:
          expr: V.three
```

The `three` action is always allowed (as expected), but the `one` and `two` actions flip between allowed and denied on each evaluation.
