### ISSUE TITLE
Breaking change b/w cerbos v0.29.0 and dev

### ISSUE THREAD

**Issue by dbuduev** [cerbos/cerbos#1798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```yaml
---
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: default
  resource: missing_attr
  variables:
    local:
      eng: P.attr.is_engineer
  rules:
    - actions:
        - use
      effect: EFFECT_ALLOW
      roles:
        - user
      condition:
        match:
          any:
            of:
              - expr: V.eng && P.attr.org == "org-1"
              - expr: P.attr.email == "info@example.com"
```

This policy returns "EFFECT_DENY" if the email is present, but the `is_engineer` attribute is missing. The problem is with `&&` in the first expression. `V.eng` is nil, so CEL results in `no such overload`. 

The workaround is the explicit comparison with true value: `V.eng == true && P.attr.org == "org-1"`.

The problem appeared first in this [PR](https://github.com/cerbos/cerbos/pull/1717), which updated CEL to v0.17. Thanks to @rcrowe for pinpointing it.

Here's the [failing test](https://github.com/cerbos/cerbos/pull/1797).
