### ISSUE TITLE
Inconsistent YAML parsing between schema validation and policy loading

### ISSUE THREAD

**Issue by haines** [cerbos/cerbos#1883]
We use github.com/ghodss/yaml (which uses gopkg.in/yaml.v2 under the hood) to convert YAML to JSON for policy parsing but gopkg.in/yaml.v3 to parse YAML for schema validation.

That means that the following policy passes schema validation but then cannot be loaded:

```yaml
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  resource: foo
  version: yes
```

The error should be `file is not valid: [/resourcePolicy/version: expected string, but got boolean]`, but instead we get `failed to unmarshal JSON: proto: (line 1:80): invalid value for string type: true`.

We should use the same YAML parser in both places.
