### ISSUE TITLE
Make DBConnectionRetries configurable

### ISSUE THREAD

**Issue by stevenbressey** [cerbos/cerbos#1919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

We have an issue using cerbos in gitlab CI with postgres as storage driver.
Sometimes, postgresql service container does not start quickly enough and cerbos fails to start after 3 db connection retries.
I tried waiting for postgres to be ready overriding the entrypoint but netcat is not available in the cerbos Docker image and we can't install it because it's based on SCRATCH.
If we could have `DBConnectionRetries` (currently a hardcoded const in https://github.com/cerbos/cerbos/blob/main/internal/storage/db/internal/funcs.go) configurable via args, it would fix the issue.
Or eventually add netcat in the cerbos Docker image.

Here is an example of our gitlab CI config: 
```yaml
test:
  stage: test
  services:
    - postgres:13.12-alpine
    - name: ghcr.io/cerbos/cerbos:0.30.0
      alias: cerbos
      command:
        - server
        - --set=server.adminAPI.enabled=true
        - --set=server.adminAPI.adminCredentials.username=${CERBOS_ADMIN_USERNAME}
        - --set=server.adminAPI.adminCredentials.passwordHash=${CERBOS_ADMIN_PASSWORD}
        - --set=storage.driver=postgres
        - --set=storage.postgres.skipSchemaCheck=true
        - --set=storage.postgres.url=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=disable&search_path=cerbos
  variables:
    CI_DEBUG_SERVICES: "true"
    POSTGRES_HOST: postgres
    POSTGRES_DB: test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: xxxxx
    CERBOS_ADMIN_USERNAME: cerbos
    CERBOS_ADMIN_PASSWORD: xxxx
```

### What would the ideal solution look like to you?

Have DBConnectionRetries configurable via args
Else, have netcat available in docker image
