### ISSUE TITLE
Ability to produce output when the rule condition is not satisfied

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#1920]
Currently the output block is only evaluated if the rule is actually activated (action, roles and conditions are satisfied). In certain situations, it's desirable to produce output when the rule is nearly activated (action and roles match but the condition is not satisfied).

In order to maintain backward compatibility, reduce noise, and to keep policy execution as fast as possible (outputs incur a tiny overhead), the proposal is to let users add an optional `when` section to the `output` block to opt into this behaviour.

```yaml
    - actions: ['view']
      effect: EFFECT_ALLOW
      roles: ['user']
      condition:
        match:
          expr: timestamp(R.expiry_date) > now()
      output: 
        expr: >
          format("%d hours until expiry", (timestamp(R.expiry_date) - now()).getHours())
        when:
          cond_fail: >
            format("expired on %s", R.expiry_date)
``` 

When evaluating the above rule,
- if the action, roles and condition match, output will be the result of evaluating `output.expr`
- If the condition is not satisfied, output will be the result of evaluating `output. when.cond_fail` if it exists. Otherwise no output will be produced.
