### ISSUE TITLE
Omitting an expectation from a test should imply `EFFECT_DENY`

### ISSUE THREAD

**Issue by haines** [cerbos/cerbos#2115]
Create a directory containing a single file named `example_test.yaml` with the following contents.
```yaml
name: Example test suite

principals:
  admin:
    id: admin
    roles:
      - admin

resources:
  example:
    kind: example
    id: example

tests:
  - name: Example test
    input:
      principals:
        - admin
      resources:
        - example
      actions:
        - create
        - update
    expected:
      - principal: admin
        resource: example
        actions:
          create: EFFECT_ALLOW
```

Running `cerbos compile .` in the directory should result in an error because the `update` action is missing from the expectations. However, it actually results in a test failure, with `EFFECT_UNSPECIFIED` as the expected value.

```console
$ cerbos compile .
Test results
└─┬Example test suite (example_test.yaml) [2 FAILED]
  └─┬Example test
    └─┬admin
      └─┬example
        ├─┬create [FAILED]
        │ └──OUTCOME: expected: EFFECT_ALLOW, actual: EFFECT_DENY
        └─┬update [FAILED]
          └──OUTCOME: expected: EFFECT_UNSPECIFIED, actual: EFFECT_DENY

2 tests executed [2 FAILED]
cerbos: error: tests failed
```
