### ISSUE TITLE
Spurious "more than one YAML document detected" error caused by trailing whitespace in policy

### ISSUE THREAD

**Issue by haines** [cerbos/cerbos#2118]
Adding trailing spaces causes an otherwise valid policy to fail to load with "more than one YAML document detected"

```yaml
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  resource: example
  version: default
  rules:
    - actions:
        - view
      effect: EFFECT_ALLOW
      roles:
        - user
      condition:
        match:
          expr: request.principal.attr.ip.inIPAddrRange("10.20.0.0/16")
            

```

Note the whitespace at the end of the file:

```
apiVersion:·api.cerbos.dev/v1⏎
resourcePolicy:⏎
··resource:·example⏎
··version:·default⏎
··rules:⏎
····-·actions:⏎
········-·view⏎
······effect:·EFFECT_ALLOW⏎
······roles:⏎
········-·user⏎
······condition:⏎
········match:⏎
··········expr:·request.principal.attr.ip.inIPAddrRange("10.20.0.0/16")⏎
············⏎
⏎
```

I'm not sure if this should be allowed by the YAML spec or not, but I've tried a few other parsers/validators and have yet to find one that rejects it. Either way, it's definitely not multiple YAML documents.
