### ISSUE TITLE
Spurious "more than one YAML document detected" caused by bad indentation

### ISSUE THREAD

**Issue by haines** [cerbos/cerbos#2146]
Related: #2118 

```yaml
apiVersion: api.cerbos.dev/v1
principalPolicy:
  principal: bad_cel_expr
  version: default
  rules:
    - resource: leave_request
      actions:
        - action: "*"
          condition:
            match:
              expr: >
                bad
              bad
          effect: EFFECT_ALLOW
```

```console
$ cerbos compile .
Load failures
bad_cel_expr.yaml more than one YAML document detected

cerbos: error: failed to compile
```
