### ISSUE TITLE
Multiple principals and/or multiple resources in a test case

### ISSUE THREAD

**Issue by mbaev** [cerbos/cerbos#2183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hello,

I have 18 variations of a resource, 33 principals, and 5 actions.
There are several hundred cases where users suppose have access to certain resources. 
![image](https://github.com/cerbos/cerbos/assets/6450526/e4b0c7af-5014-4fc6-bbbc-2fc56610047b)

It's hard to define and then manage test suits even reusing some definitions.

## Solution
It would be awesome if it's possible to define multiple principals that suppose to perform several actions over several resources (technically speaking, it's several variations of one resource).

Having that we could replace this
```yaml
---
name: CenterTestSuite
description: Tests to verify the "center" resource policies

tests:
  - name: Accessing a Center by basic principals
    input:
      auxData: sameTenantJWT
      resources:
        - sameTenantPublishedEnabledCenter
        - sameTenantPublishedDisabledCenter
        - sameTenantUnpublishedEnabledCenter
        - sameTenantUnpublishedDisabledCenter

        - anotherTenantPublishedEnabledCenter
        - anotherTenantPublishedDisabledCenter
        - anotherTenantUnpublishedEnabledCenter
        - anotherTenantUnpublishedDisabledCenter
      actions:
        - create
        - read
        - update
        - delete
      principals:
        - guest
        - sameTenantUser
        - anotherTenantUser

        - ADMINISTER_TENANTS
        - ADMINISTER_USERS
        - ADMINISTER_PERMISSIONS
        - ADMINISTER_DATABASES
        - ADMINISTER_CENTERS
        - ADMINISTER_PRODUCTS
        - ADMINISTER_NODES
        - ADMINISTER_FILE_STORAGE
        - MANAGE_USER_CONTENT
        - MANAGE_DATA

        - SAME_TENANT_ADMINISTER_TENANT_USERS
        - SAME_TENANT_ADMINISTER_TENANT_PERMISSIONS
        - SAME_TENANT_ADMINISTER_TENANT_DATABASES
        - SAME_TENANT_ADMINISTER_TENANT_CENTERS
        - SAME_TENANT_ADMINISTER_TENANT_PRODUCTS
        - SAME_TENANT_ADMINISTER_TENANT_NODES
        - SAME_TENANT_ADMINISTER_TENANT_FILE_STORAGE
        - SAME_TENANT_MANAGE_TENANT
        - SAME_TENANT_MANAGE_TENANT_USER_CONTENT
        - SAME_TENANT_MANAGE_TENANT_DATA

        - ANOTHER_TENANT_ADMINISTER_TENANT_USERS
        - ANOTHER_TENANT_ADMINISTER_TENANT_PERMISSIONS
        - ANOTHER_TENANT_ADMINISTER_TENANT_DATABASES
        - ANOTHER_TENANT_ADMINISTER_TENANT_CENTERS
        - ANOTHER_TENANT_ADMINISTER_TENANT_PRODUCTS
        - ANOTHER_TENANT_ADMINISTER_TENANT_NODES
        - ANOTHER_TENANT_ADMINISTER_TENANT_FILE_STORAGE
        - ANOTHER_TENANT_MANAGE_TENANT
        - ANOTHER_TENANT_MANAGE_TENANT_USER_CONTENT
        - ANOTHER_TENANT_MANAGE_TENANT_DATA
    expected:
      - resource: sameTenantPublishedEnabledCenter
        principal: ADMINISTER_CENTERS
        actions: &full_access
          create: EFFECT_ALLOW
          read: EFFECT_ALLOW
          update: EFFECT_ALLOW
          delete: EFFECT_ALLOW
      - resource: sameTenantPublishedDisabledCenter
        principal: ADMINISTER_CENTERS
        actions: *full_access
      - resource: sameTenantUnpublishedEnabledCenter
        principal: ADMINISTER_CENTERS
        actions: *full_access
      - resource: sameTenantUnpublishedDisabledCenter
        principal: ADMINISTER_CENTERS
        actions: *full_access

      - resource: anotherTenantPublishedEnabledCenter
        principal: ADMINISTER_CENTERS
        actions: *full_access
      - resource: anotherTenantPublishedDisabledCenter
        principal: ADMINISTER_CENTERS
        actions: *full_access
      - resource: anotherTenantUnpublishedEnabledCenter
        principal: ADMINISTER_CENTERS
        actions: *full_access
      - resource: anotherTenantUnpublishedDisabledCenter
        principal: ADMINISTER_CENTERS
        actions: *full_access

      - resource: sameTenantPublishedEnabledCenter
        principal: SAME_TENANT_ADMINISTER_TENANT_CENTERS
        actions: *full_access
      - resource: sameTenantPublishedDisabledCenter
        principal: SAME_TENANT_ADMINISTER_TENANT_CENTERS
        actions: *full_access
      - resource: sameTenantUnpublishedEnabledCenter
        principal: SAME_TENANT_ADMINISTER_TENANT_CENTERS
        actions: *full_access
      - resource: sameTenantUnpublishedDisabledCenter
        principal: SAME_TENANT_ADMINISTER_TENANT_CENTERS
        actions: *full_access
```
with this
```yaml
---
name: CenterTestSuite
description: Tests to verify the "center" resource policies

tests:
  - name: Accessing a Center by basic principals
    input:
      auxData: sameTenantJWT
      resources:
        - sameTenantPublishedEnabledCenter
        - sameTenantPublishedDisabledCenter
        - sameTenantUnpublishedEnabledCenter
        - sameTenantUnpublishedDisabledCenter

        - anotherTenantPublishedEnabledCenter
        - anotherTenantPublishedDisabledCenter
        - anotherTenantUnpublishedEnabledCenter
        - anotherTenantUnpublishedDisabledCenter
      actions:
        - create
        - read
        - update
        - delete
      principals:
        - guest
        - sameTenantUser
        - anotherTenantUser

        - ADMINISTER_TENANTS
        - ADMINISTER_USERS
        - ADMINISTER_PERMISSIONS
        - ADMINISTER_DATABASES
        - ADMINISTER_CENTERS
        - ADMINISTER_PRODUCTS
        - ADMINISTER_NODES
        - ADMINISTER_FILE_STORAGE
        - MANAGE_USER_CONTENT
        - MANAGE_DATA

        - SAME_TENANT_ADMINISTER_TENANT_USERS
        - SAME_TENANT_ADMINISTER_TENANT_PERMISSIONS
        - SAME_TENANT_ADMINISTER_TENANT_DATABASES
        - SAME_TENANT_ADMINISTER_TENANT_CENTERS
        - SAME_TENANT_ADMINISTER_TENANT_PRODUCTS
        - SAME_TENANT_ADMINISTER_TENANT_NODES
        - SAME_TENANT_ADMINISTER_TENANT_FILE_STORAGE
        - SAME_TENANT_MANAGE_TENANT
        - SAME_TENANT_MANAGE_TENANT_USER_CONTENT
        - SAME_TENANT_MANAGE_TENANT_DATA

        - ANOTHER_TENANT_ADMINISTER_TENANT_USERS
        - ANOTHER_TENANT_ADMINISTER_TENANT_PERMISSIONS
        - ANOTHER_TENANT_ADMINISTER_TENANT_DATABASES
        - ANOTHER_TENANT_ADMINISTER_TENANT_CENTERS
        - ANOTHER_TENANT_ADMINISTER_TENANT_PRODUCTS
        - ANOTHER_TENANT_ADMINISTER_TENANT_NODES
        - ANOTHER_TENANT_ADMINISTER_TENANT_FILE_STORAGE
        - ANOTHER_TENANT_MANAGE_TENANT
        - ANOTHER_TENANT_MANAGE_TENANT_USER_CONTENT
        - ANOTHER_TENANT_MANAGE_TENANT_DATA
    expected:
      - principal: ADMINISTER_CENTERS
        resources:
        - sameTenantPublishedEnabledCenter
        - sameTenantPublishedDisabledCenter
        - sameTenantUnpublishedEnabledCenter
        - sameTenantUnpublishedDisabledCenter
        - anotherTenantPublishedEnabledCenter
        - anotherTenantPublishedDisabledCenter
        - anotherTenantUnpublishedEnabledCenter
        - anotherTenantUnpublishedDisabledCenter
        actions: &full_access
          create: EFFECT_ALLOW
          read: EFFECT_ALLOW
          update: EFFECT_ALLOW
          delete: EFFECT_ALLOW

      - principal: SAME_TENANT_ADMINISTER_TENANT_CENTERS
        resources:
          - sameTenantPublishedEnabledCenter
          - sameTenantPublishedDisabledCenter
          - sameTenantUnpublishedEnabledCenter
          - sameTenantUnpublishedDisabledCenter
        actions: *full_access
```
pay attention that here I'm using keyword "resources". It might make sense to differentiate resource definitions for one or multiple resources.

It would be helpful to have same thing for "principals".

### What would the ideal solution look like to you?

It would be helpful to be able to use keywords "principals" and "resources" instead of "principal" and "resource". Though I'm thinking these ones should stay for backward compatibility and cases when people don't need to define many resources and/or principals. In the meantime, to resolve conflict of the keywords priorities can be introduced. If both conflicting keywords are used then Cerbos would throw an exception like "Conflicting keywords are being used. Please use either keyword "resource" to define one resource or "resources" to define multiple resources for test case ...".

### Anything else?

Taking an example:
```yaml
---
name: ExampleTestSuite
description: Tests to verify resource policies

tests:
  - name: Accessing a Resource by basic principals
    input:
      auxData: validJWT
      resources:
        - resource1
        - resource2
        - resource3
      actions:
        - create
        - read
        - update
        - delete
      principals:
        - principal1
        - principal2
        - principal3
    expected:
      - principals:
        - principal1
        - principal2
        resources:
        - resource1
        - resource2
        actions:
          create: EFFECT_ALLOW
          read: EFFECT_ALLOW
          update: EFFECT_ALLOW
```
I would assume that principals "principal1" and "principal2" suppose to "create", "read", and "update" any of resources "resource1" or "resource2".

**Comment by charithe** [comment]
Hi. If I understood you correctly, you'd like to group the expectations by principal to avoid having to repeat each principal+resource+action combination?

**Comment by mbaev** [comment]
Sorry that I wasn't clear, but you got exactly what I meant. I would be convenient to be able to group principals and/or resources to define expectations.

Thank you

**Comment by charithe** [comment]
Thanks. I definitely see the value of being able to group things to avoid the verbosity. Making the test framework less verbose and easier to use is one of the things in our radar. It's a bit complicated by the fact that changes like this are breaking changes and we need a strategy to painlessly migrate existing users without any disruption.

In the mean time, if you don't mind integrating another tool into your workflow, here's how you might be able to generate the tests for all the combinations of resources and principals using [ytt](https://carvel.dev/ytt/docs/v0.49.x/install/).

```yaml
#@ def full_access():
create: EFFECT_ALLOW
read: EFFECT_ALLOW
update: EFFECT_ALLOW
delete: EFFECT_ALLOW
#@ end

#@ def principal_resource_actions():
ADMINISTER_CENTERS:
  resources:
    - sameTenantPublishedEnabledCenter
    - sameTenantPublishedDisabledCenter
    - sameTenantUnpublishedEnabledCenter
    - sameTenantUnpublishedDisabledCenter
    - anotherTenantPublishedEnabledCenter
    - anotherTenantPublishedDisabledCenter
    - anotherTenantUnpublishedEnabledCenter
    - anotherTenantUnpublishedDisabledCenter
  actions: #@ full_access()

SAME_TENANT_ADMINISTER_TENANT_CENTERS:
  resources:
    - sameTenantPublishedEnabledCenter
    - sameTenantPublishedDisabledCenter
    - sameTenantUnpublishedEnabledCenter
    - sameTenantUnpublishedDisabledCenter
  actions: #@ full_access()
#@ end

---
name: CenterTestSuite
description: Tests to verify the "center" resource policies
tests:
  - name: Accessing a Center by basic principals
    input:
      auxData: sameTenantJWT
      resources:
        - sameTenantPublishedEnabledCenter
        - sameTenantPublishedDisabledCenter
        - sameTenantUnpublishedEnabledCenter
        - sameTenantUnpublishedDisabledCenter

        - anotherTenantPublishedEnabledCenter
        - anotherTenantPublishedDisabledCenter
        - anotherTenantUnpublishedEnabledCenter
        - anotherTenantUnpublishedDisabledCenter
      actions:
        - create
        - read
        - update
        - delete
      principals:
        - guest
        - sameTenantUser
        - anotherTenantUser

        - ADMINISTER_TENANTS
        - ADMINISTER_USERS
        - ADMINISTER_PERMISSIONS
        - ADMINISTER_DATABASES
        - ADMINISTER_CENTERS
        - ADMINISTER_PRODUCTS
        - ADMINISTER_NODES
        - ADMINISTER_FILE_STORAGE
        - MANAGE_USER_CONTENT
        - MANAGE_DATA

        - SAME_TENANT_ADMINISTER_TENANT_USERS
        - SAME_TENANT_ADMINISTER_TENANT_PERMISSIONS
        - SAME_TENANT_ADMINISTER_TENANT_DATABASES
        - SAME_TENANT_ADMINISTER_TENANT_CENTERS
        - SAME_TENANT_ADMINISTER_TENANT_PRODUCTS
        - SAME_TENANT_ADMINISTER_TENANT_NODES
        - SAME_TENANT_ADMINISTER_TENANT_FILE_STORAGE
        - SAME_TENANT_MANAGE_TENANT
        - SAME_TENANT_MANAGE_TENANT_USER_CONTENT
        - SAME_TENANT_MANAGE_TENANT_DATA

        - ANOTHER_TENANT_ADMINISTER_TENANT_USERS
        - ANOTHER_TENANT_ADMINISTER_TENANT_PERMISSIONS
        - ANOTHER_TENANT_ADMINISTER_TENANT_DATABASES
        - ANOTHER_TENANT_ADMINISTER_TENANT_CENTERS
        - ANOTHER_TENANT_ADMINISTER_TENANT_PRODUCTS
        - ANOTHER_TENANT_ADMINISTER_TENANT_NODES
        - ANOTHER_TENANT_ADMINISTER_TENANT_FILE_STORAGE
        - ANOTHER_TENANT_MANAGE_TENANT
        - ANOTHER_TENANT_MANAGE_TENANT_USER_CONTENT
        - ANOTHER_TENANT_MANAGE_TENANT_DATA
    expected:
      #@ for principal in principal_resource_actions():
      #@ resources = principal_resource_actions()[principal]["resources"]
      #@ actions = principal_resource_actions()[principal]["actions"]
      #@ for resource in resources:
      - resource: #@ resource
        principal: #@ principal
        actions: #@ actions
      #@ end
      #@ end
```

Saving the above as `.center_test_template.yaml` and running `ytt -f .center_test_template.yaml` produces the test file from your example above.
