### ISSUE TITLE
Can start server without a port

### ISSUE THREAD

**Issue by alexolivier** [cerbos/cerbos#22]
My config file was formatted badly and the port variable wasn't defined, but the server still started (but didn't listen). Would be better if it exited with an error as it _looked_ like it was working.

```
---
server:
listenAddr: ":9999"

storage:
  driver: "disk" # Valid values are "disk" or "git"
  disk: # Only required if "driver" is "disk"
    directory: /policies
    readOnly: true # Set to false if you want to write new policies to disk through

```

```
2021-03-25T09:49:48.233Z	INFO	cerbos.disk.store	Creating read-only disk store	{"root": "/policies"}
2021-03-25T09:49:48.236Z	INFO	cerbos.http.server	Starting HTTP server on
```
