### ISSUE TITLE
Derived roles don't work

### ISSUE THREAD

**Issue by Damcios-s** [cerbos/cerbos#2262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Derived roles are not applied to principals and policies based on derived roles don't work.

### Expected Behavior

Derived roles should be correctly applied.

### Steps To Reproduce

1. Go to Cerbos Playground: https://play.cerbos.dev/new?generator
2. Generate a new project
3. Add a derived roles file `/derived_roles/common_roles.yaml`

```yaml
# yaml-language-server: $schema=https://api.cerbos.dev/latest/cerbos/policy/v1/Policy.schema.json
# docs: https://docs.cerbos.dev/cerbos/latest/policies/derived_roles
apiVersion: api.cerbos.dev/v1
derivedRoles:
  name: common_roles
  definitions:
    - name: owner
      parentRoles:
        - user
      condition:
        match:
          expr: request.resource.attr.ownerId == request.principal.id
```

4. Edit the test resouces file `resource_policies/testdata/resources.yaml` to add the `ownerId: user#1` attribute to the resource.

```yaml
# yaml-language-server: $schema=https://api.cerbos.dev/latest/cerbos/policy/v1/TestFixture/Resources.schema.json
# docs: https://docs.cerbos.dev/cerbos/latest/policies/compile#_sharing_test_fixtures

resources:
  basicResource#1:
    id: basicResource#1
    kind: basicResource
    attr: {
      ownerId: user#1
    }
```

5. Edit the resource policy for any action to allow the 'owner' role instead of the 'user' role and import the created derived common_roles.

```yaml
# yaml-language-server: $schema=https://api.cerbos.dev/latest/cerbos/policy/v1/Policy.schema.json
# docs: https://docs.cerbos.dev/cerbos/latest/policies/resource_policies

apiVersion: api.cerbos.dev/v1
resourcePolicy:
  importDerivedRoles:
    - common_roles
  resource: basicResource
  version: default
  rules:
    - actions:
        - create
      effect: EFFECT_ALLOW
      roles:
        - user
        - admin
    - actions:
        - read
      effect: EFFECT_ALLOW
      roles:
        - owner
        - admin
    - actions:
        - update
      effect: EFFECT_ALLOW
      roles:
        - user
        - admin
    - actions:
        - delete
      effect: EFFECT_ALLOW
      roles:
        - admin
```

6. When the tests now run, user#1 will not be allowed to read basicResource#1 even though basicResource#1 has the correct ownerId attribute.  

Adding the condition `request.resource.attr.ownerId == request.principal.id` in the resource policy itself does work as expected. 

### Environment

```markdown
- Cerbos Playground: https://play.cerbos.dev/new?generator
```

**Comment by charithe** [comment]
Hello. You need to be explicit in the resource policy that you're trying to use a derived role. So, the rule should read as follows:

```yaml
    - actions:
        - read
      effect: EFFECT_ALLOW
      derivedRoles:
        - owner
      roles:
        - admin
```
