### ISSUE TITLE
Support for creating ingress via Helm chart

### ISSUE THREAD

**Issue by klafbang** [cerbos/cerbos#2344]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature description

Right now, I can deploy Cerbos using the helm chart.  I can expose it directly and use a fixed certificate.  The documentation says I have to use cluster functionality if I want to change certificates.

Many charts support creating an ingress for a ClusterIP exposed service.  It would be useful for Cerbos to do this as well.

### What would the ideal solution look like to you?

From the Gitlab chart's values file, I use this configuration

```
  ## https://docs.gitlab.com/charts/charts/globals#configure-ingress-settings
  ingress:
    apiVersion: ""
    provider: nginx
    class: nginx
    annotations:
      kubernetes.io/tls-acme: true
      nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    enabled: true
    tls:
      enabled: true
        #  secretName: gitlab-pages-tls
    path: /
    pathType: Prefix
```

The provider, class, path, and pathType are a little non-standard, but most charts support a similar structure: enabling an ingress, optionally enabling tls and setting a user-specified set of annotations.

Here's Bitnami's WordPress chart's configuration of same:

```
ingress:
  enabled: true
  pathType: ImplementationSpecific
  apiVersion: ""
  ingressClassName: ""
  hostname: westergaard.eu
  path: /
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.provider: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tlsWwwPrefix: false
  selfSigned: false
  extraHosts: []
  extraPaths: []
  extraTls:
    - hosts: 
         - westergaard.eu
      secretName: westergaard-eu-tls
  secrets: []
  extraRules: []
```

The most important difference is the configuration of the hostname.  This ingress also supports adding additional hostnames.

This is the ingress I have configured manually for nginx-ingress with certbot annotations:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  labels:
    environment: acceptance
  name: cerbos-ingress
spec:
  rules:
  - host: cerbos.acceptance.gf.ocs.nu
    http:
      paths:
      - backend:
          service:
            name: cerbos
            port:
              number: 3592
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - cerbos.acceptance.gf.ocs.nu
    secretName:  cerbos-ingress-tls
```

For Cerbos it maybe makes sense to be able to expose both the http and grpc endpoints.  Note that grpc requires extra annotations to work via the ingress; here's an ingress I've made for grpc for another application.  For me personally, I don't want the grpc endpoint exposed, so for the ideal solution for me it doesn't matter.  Note that name virtual servers don't work for GRPC, so it must be on another IP or port than the https endpoint, making it a possible source of confusion.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "false"
    nginx.ingress.kubernetes.io/auth-tls-secret: nuts-test/trust-tls
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-SSL-CERT $ssl_client_escaped_cert;
  name: nuts-grpc
spec:
  rules:
  - host: nuts-n2n.test.daas.nu
    http:
      paths:
      - backend:
          service:
            name: nuts
            port:
              number: 5555
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - nuts-n2n.test.daas.nu
    secretName: nuts-development-tls
```

This ingress also offloads client certificate verification + forwards the client certificate, which is likely not necessary for Cerbos.  This ingress explicitly disabled automatic certificate provisioning.
