### ISSUE TITLE
Add SASL support for audit logs sending to Kafka

### ISSUE THREAD

**Issue by waihong** [cerbos/cerbos#2348]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature description

As of now, the audit configuration supports only TLS for Kafka. It would be good to add SASL as an additional authentication mechanism so that it can send directly to a topic in Confluent Cloud. The current workaround is to use a Kafka proxy in between.

### What would the ideal solution look like to you?

Extend configuration for SASL:

```
audit:
  kafka:
    sasl:
      method: PLAIN
      username: ${USERNAME}
      password: ${PASSWORD}
```
