### ISSUE TITLE
Fail compilation if condition uses field not in schema

### ISSUE THREAD

**Issue by jbeisen** [cerbos/cerbos#2366]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature description

For a principal schema like this:
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Principal",
  "type": "object",
  "properties": {},
  "required": [],
  "additionalProperties": false
}
```

And a resource policy like this:
```
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: "project"
  schemas:
    principalSchema:
      ref: cerbos:///principal.json
  rules:
    - name: user-rule
      effect: EFFECT_ALLOW
      roles:
        - user
      actions: ["read"]
      condition:
        match:
          expr: request.principal.attr.foo == "bar"
```

Cerbos currently compiles this policy fine. However logically I think this should fail because the rule expects the principal to have attribute `foo`, but the schema makes that impossible.

### What would the ideal solution look like to you?

Compilation fails with an error message like `Rule x references principal attribute not in principal schema`.
