### ISSUE TITLE
Use sigstore tools to sign artifacts and distribute them through an OCI registry

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos#239]
[Sigstore](https://www.sigstore.dev) is a suite of tools for software supply chain security. [Cosign](https://github.com/sigstore/cosign) the signing tool is now stable and can be used to sign and distribute containers AND binary blobs using an OCI registry (both GitHub and JFrog are supported).

The [keyless signing mode](https://github.com/sigstore/cosign/blob/main/KEYLESS.md) is still experimental though. When it becomes stable, we should configure CI to sign all artifacts during the release. 

To do:

- [ ] Wait for keyless mode to be stable (because managing keys manually with a KMS is a bit of a faff)
- [ ] Pick a Google account from @cerbos.dev  to be the signer
- [ ] Configure CI to sign containers, binaries and any other artifacts
- [ ] Use the same OCI registry as the containers to distribute binaries as well (see https://oras.land)  

```sh
COSIGN_EXPERIMENTAL=1 cosign verify ghcr.io/cerbos/cerbos:0.4.0

Verification for ghcr.io/cerbos/cerbos:0.4.0 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - Any certificates were verified against the Fulcio roots.

Certificate subject:  [charith@cerbos.dev]
{"critical":{"identity":{"docker-reference":"ghcr.io/cerbos/cerbos"},"image":{"docker-manifest-digest":"sha256:7d9e3a7766c1f94288d11a2f3490c1c19f5b9e469027e4cb3394fe6a02d45049"},"type":"cosign container image signature"},"optional":null}
```

**Comment by charithe** [comment]
Cosign has experimental support for signing using the GitHub OIDC -- which means we don't have to manage a private key separately. Unfortunately, as of 08-11-2021, the Rekor transparency log is not fully functional:

```
Error: signing dist/actions-test_0.1.0-prerelease_Darwin_all.tar.gz: Post "https://rekor.sigstore.dev/api/v1/log/entries": context deadline exceeded
main.go:48: error during command execution: signing dist/actions-test_0.1.0-prerelease_Darwin_all.tar.gz: Post "https://rekor.sigstore.dev/api/v1/log/entries": context deadline exceeded
```

Signing config:

```yaml
# GH Actions
      - uses: sigstore/cosign-installer@main

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --config=.goreleaser-ci.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_EXPERIMENTAL: "1"
```

```yaml
# Goreleaser
   signs:
     - id: cosign
       cmd: cosign
       args: ["sign-blob", "-output=${signature}", "${artifact}"]
       artifacts: all
```
