### ISSUE TITLE
Plan incomplete with lenient scope search

### ISSUE THREAD

**Issue by giacinti** [cerbos/cerbos#2462]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

With lenient scope search activated in the engine, if we define a general policy for resources with scope `acme` and another specialized one for the same resources kind with scope `acme.1234`, the `CheckResources` works as expected but the `PlanResources` ignores the specialized policy.

### Expected Behavior

The PlanResources takes the specialized policy in account when generating the condition filter

### Steps To Reproduce

With lenient scope search activated in the engine.
Here is a simple example exhibiting the issue. We need 3 resource policies:
- resource-default.yaml
```yaml
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  resource: res
  version: default
  rules:
    - actions: ["*"]
      roles: ["*"]
      effect: EFFECT_DENY
```
- resource.yaml
```yaml
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  resource: res
  version: default
  scope: acme

  rules:
    - actions:
        - doit
      effect: EFFECT_ALLOW
      roles: ["*"]
      condition:
        match:
          expr: P.attr.domain==R.attr.domain
```
- resource-1234.yaml
```yaml
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  resource: res
  version: default
  scope: acme.1234

  rules:
    - actions:
        - doit
      effect: EFFECT_DENY
      roles: ["*"]
      condition:
        match:
          expr: >
            P.id=="not-you"
```

When calling the REST API with this request:
```shell
cat <<EOF | curl --silent "localhost:3592/api/plan/resources?pretty" -d @-
{
  "requestId":  "test01",
  "action":  "doit",
  "resource":  {
    "kind":  "res",
    "scope": "acme"
  },
  "principal":  {
    "id":  "not-you",
    "roles":  ["user"],
    "attr": {
      "domain": "example.com"
    }
  },
  "includeMeta": true
}
EOF
```
the answer is:
```json
{
  "requestId": "test01",
  "action": "doit",
  "resourceKind": "res",
  "filter": {
    "kind": "KIND_CONDITIONAL",
    "condition": {
      "expression": {
        "operator": "eq",
        "operands": [
          {
            "value": "example.com"
          },
          {
            "variable": "request.resource.attr.domain"
          }
        ]
      }
    }
  },
  "meta": {
    "filterDebug": "(eq \"example.com\" request.resource.attr.domain)",
    "matchedScope": "acme"
  },
  "cerbosCallId": "01JJWBNSB28YEVBAPXVVBDWQYF"
}
```
there is nothing in this plan about the fact that `not-you` cannot execute the `doit` action on the resources with scope `acme.1234` (although this can be verified by calling `/check/resources`)
the expected result would be something like:
```json
{
  "requestId": "test01",
  "action": "doit",
  "resourceKind": "res",
  "filter": {
    "kind": "KIND_CONDITIONAL",
    "condition": {
      "expression": {
        "operator": "and",
        "operands": [
          {
            "expression": {
              "operator": "not",
              "operands": [
                {
                  "expression": {
                    "operator": "eq",
                    "operands": [
                      {
                        "variable": "request.resource.scope"
                      },
                      {
                        "value": "acme.1234"
                      }
                    ]
                  }
                }
              ]
            }
          },
          {
            "expression": {
              "operator": "eq",
              "operands": [
                {
                  "value": "example.com"
                },
                {
                  "variable": "request.resource.attr.domain"
                }
              ]
            }
          }
        ]
      }
    }
  },
  "meta": {
    "filterDebug": "(and (not (eq request.resource.scope \"acme.1234\")) (eq \"example.com\" request.resource.attr.domain))",
    "matchedScope": "acme"
  },
  "cerbosCallId": "01JJWBN1BWZY0DT4TVNNBZCN3V"
}
```

### Environment

```markdown
- OS: Amazon Linux 2 (Cerbos is installed as a service in EKS)
- Cerbos version: 0.40.0
```

### Anything else?

The valid plan has been generated in tweaking the top level policy `resource.yaml`:
```yaml
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  resource: res
  version: default
  scope: acme

  rules:
    - actions:
        - doit
      effect: EFFECT_ALLOW
      roles: ["*"]
      condition:
        match:
          expr: P.attr.domain==R.attr.domain

    - actions:
        - doit
      effect: EFFECT_DENY
      roles: ["*"]
      condition:
        match:
          expr: P.id=="not-you" && R.scope=="acme.1234"
```
so it really looks like only the first policy found is taken in account for the plan
