### ISSUE TITLE
Block condition operators not evaluating correctly in REPL

### ISSUE THREAD

**Issue by HerrSpeck** [cerbos/cerbos#2510]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Hi!
I ran into an issue a couple days ago, where one of my policies using nested all-any-all operators does not evaluate correctly.

I have the following policy for my `Permission`-Resource:
```yaml
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: default
  resource: Permission
  variables:
    import: [claim_variables]
  rules:
    - actions: [create]
      effect: EFFECT_ALLOW
      roles: [USER, ADMIN]
      condition:
        match:
          all:
            of:
              - expr: V.claim_permission_administration # -> "CLAIM_PERMISSION_ADMINISTRATION" in P.attr.claims
              - expr: R.attr.externalId == "null"
              - any:
                  of:
                   - expr: V.claim_long_term # -> "CLAIM_LONG_TERM_ADMINISTRATION" in P.attr.claims
                   - all:
                       of:
                         - expr: R.attr.beginDate != "*"
                         - expr: R.attr.endDate != "*"
                         - expr: timestamp(R.attr.endDate) - timestamp(R.attr.beginDate) <= duration("%dh".format([int(P.attr.guiDefaults.maxPermissionInterval) * 24]))
```

This policy is not evaluated correctly. If either the `V.claim_long_term` condition is false, or the nested `all` is false, the `any` is also false even though it should be true (since only one of the cases is false) and therefore, the entire policy fails.

### Expected Behavior

The [documentation](https://docs.cerbos.dev/cerbos/latest/policies/conditions.html#_expressions_and_blocks) states, that operators can be nested. Therefore, I would expect this policy to evaluate the `any` correctly, based on the nested conditions.

At the moment, we can work around this by removing the `any`-condition entirely and putting the conditions into a single logical expression like this:
```yaml
- expr: V.claim_long_term || (R.attr.beginDate != "*" && R.attr.endDate != "*" && timestamp(R.attr.endDate) - timestamp(R.attr.beginDate) <= duration("%dh".format([int(P.attr.guiDefaults.maxPermissionInterval) * 24])))
```

But adding all these conditions into one expression makes it very hard to read what is actually happening. We also have another policy that is an extension of this one and has a more complex `all` case, that is even harder to read when putting it all into one single logical expression.

### Steps To Reproduce

I'll add examples with the result from `repl`:

**EXAMPLE 1:**

Resource:
```json
{
  "kind": "Permission",
  "id": "0671c852-45e3-4814-a0db-69fd3bc83995",
  "attr": {
    "beginDate": "*",
    "endDate": "*",
    "externalId": "null"
  }
}
```

Principal:
```json
{
  "id": "0612ecc1-8057-455e-821f-140a6c6b0842",
  "roles": [
    "ADMIN"
  ],
  "attr": {
    "claims": [
      "CLAIM_PERMISSION_ADMINISTRATION"
      "CLAIM_LONG_TERM_ADMINISTRATION"
    ],
    "guiDefaults": {
      "maxPermissionInterval": 7
    }
  }
}
```

When I run this, I get the following result from `repl`:
<img width="1070" alt="Image" src="https://github.com/user-attachments/assets/2cfacab4-8290-46aa-b290-24155ca31f58" />

**EXAMPLE 2:**

Resource:
```json
{
  "kind": "Permission",
  "id": "6ddc1faa-851d-4ed7-908f-84b175fdcdaa",
  "attr": {
    "beginDate": "2025-03-13T00:00:00.000Z",
    "endDate": "2025-03-13T00:00:00.000Z",
    "externalId": "null"
  }
}
```

Principal:
```json
{
  "id": "0612ecc1-8057-455e-821f-140a6c6b0842",
  "roles": [
    "ADMIN"
  ],
  "attr": {
    "claims": [
      "CLAIM_PERMISSION_ADMINISTRATION"
    ],
    "guiDefaults": {
      "maxPermissionInterval": 7
    }
  }
}
```

When I run this, I get the following result from `repl`:

<img width="1065" alt="Image" src="https://github.com/user-attachments/assets/0ff11204-2c71-43bc-a497-034ec7243023" />

### Environment

```markdown
- OS: MacOS Sonoma 14.3
- Cerbos version: 0.41.0
- Docker version: v4.39.0
```
