### ISSUE TITLE
Incorrect rule matching caused by wildcard usage in resource names

### ISSUE THREAD

**Issue by LLLLLQ-4** [cerbos/cerbos#2590]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I am trying to protcted `/premium/*` from the other resources in parent path `/`. So I define two policies:
- **protected_resource.yaml:** All user can get an access to /*
- **premium_resource.yaml:** Only premium user can get an access to /premium/*

When I use words(i.e., "protected_resource" and "premium_resource") to define resources, it works fine as follows:
1) policy
```
# protected_resource.yaml:
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: protected_resource 
  rules:
    - actions: ["access"] 
      roles:
        - user
        - user_premium 
      effect: EFFECT_ALLOW
```
```
# premium_resource.yaml:
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: premium_resource 
  rules:
    - actions: ["access"] 
      roles:
        - user_premium 
      effect: EFFECT_ALLOW
```
2) test setup:
```
principals:
  alice:
    id: alice
    roles:
      - user 
  jdoe:
    id: jdoe
    roles:
      - user 
      - user_premium 

resources:
  my_protected_resource:
    id: resource1
    kind: protected_resource resource.

  my_premium_resource:
    id: resource2
    kind: premium_resource 
```
3) test result
```
└─┬KeycloakPolicyTestSuite (demo_test.yaml) [4 OK]
  ├─┬Protected Resource Access
  │ ├─┬alice
  │ │ └─┬my_protected_resource
  │ │   └─┬access [OK]
  │ │     └──RESULT: EFFECT_ALLOW
  │ └─┬jdoe
  │   └─┬my_protected_resource
  │     └─┬access [OK]
  │       └──RESULT: EFFECT_ALLOW
  └─┬Premium Resource Access
    ├─┬alice
    │ └─┬my_premium_resource
    │   └─┬access [OK]
    │     └──RESULT: EFFECT_DENY
    └─┬jdoe
      └─┬my_premium_resource
        └─┬access [OK]
          └──RESULT: EFFECT_ALLOW

4 tests executed [4 OK]
```

However, when I change resources into path, something wrong happens:
1) policy
```
# protected_resource.yaml:
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: /* 
  rules:
    - actions: ["access"] 
      roles:
        - user
        - user_premium 
      effect: EFFECT_ALLOW
```
```
# premium_resource.yaml:
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: /premium/* 
  rules:
    - actions: ["access"] 
      roles:
        - user_premium 
      effect: EFFECT_ALLOW
```
2) test setup:
```
principals:
  alice:
    id: alice
    roles:
      - user 
  jdoe:
    id: jdoe
    roles:
      - user 
      - user_premium 

resources:
  my_protected_resource:
    id: resource1
    kind: /* 
  my_premium_resource:
    id: resource2
    kind: /premium/*
```
3) test result
```
└─┬KeycloakPolicyTestSuite (demo_test.yaml) [3 OK] [1 FAILED]
  ├─┬Protected Resource Access
  │ ├─┬alice
  │ │ └─┬my_protected_resource
  │ │   └─┬access [OK]
  │ │     └──RESULT: EFFECT_ALLOW
  │ └─┬jdoe
  │   └─┬my_protected_resource
  │     └─┬access [OK]
  │       └──RESULT: EFFECT_ALLOW
  └─┬Premium Resource Access
    ├─┬alice
    │ └─┬my_premium_resource
    │   └─┬access [FAILED]
    │     └──OUTCOME: expected: EFFECT_DENY, actual: EFFECT_ALLOW
    └─┬jdoe
      └─┬my_premium_resource
        └─┬access [OK]
          └──RESULT: EFFECT_ALLOW


TRACES
KeycloakPolicyTestSuite - alice.my_premium_resource.access
  policy=cerbos.resource./premium/*.vdefault > action=access > scope="" > rule=rule-001 > condition
    activated
    result → true

  policy=cerbos.resource./premium/*.vdefault > action=access
    activated
    effect → allow

4 tests executed [3 OK] [1 FAILED]
cerbos: error: tests failed
```

### Expected Behavior

Both setting should act samely, but somehow Alice could get an access to /premium/*.

### Steps To Reproduce

as shown below.

### Environment

```markdown

```
