### ISSUE TITLE
cerbos-sidecar(git-pull): failed to pull from remote: worktree contains unstaged changes

### ISSUE THREAD

**Issue by michaelalang** [cerbos/cerbos#2616]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

with latest (0.44.0) cerbos container (ghcr.io/cerbos/cerbos@sha256:1cba950526a6bdbcebb1c1ccee7e02c3a8c8bfe43958d903da1b0a59dcb217d9) 

refreshing git based policies configuration seems to be broken with error:

```
{"log.level":"error","@timestamp":"2025-06-27T05:43:11.421Z","log.logger":"cerbos.git.store","message":"Failed to pull from remote","dir":"/policies","error":"worktree contains unstaged changes"}
{"log.level":"error","@timestamp":"2025-06-27T05:43:11.421Z","log.logger":"cerbos.git.store","message":"Failed to check for updates","dir":"/policies","error":"failed to pull from remote: worktree contains unstaged changes"}

```

### Expected Behavior

reloading of policies from git pull updates cerbos policies

### Steps To Reproduce

* configure cerbos in sidecar
* configure git as policy source
* volumeMount emtpyDir: {}
* start up and verify policies working
* push a valid policy change to the git repository
* encounter the error message
* encounter no updates to policies happening

```
server:
  grpcListenAddr: ":3593"
  requestLimits:
    maxActionsPerResource: 5
    maxResourcesPerRequest: 500
  advanced:
    grpc:
      maxRecvMsgSizeBytes: 8388608
  logRequestPayloads: false

engine:
  defaultPolicyVersion: "default"

storage:
  driver: "git"
  git:
    protocol: https
    url: https://github.com/..../prom-policy.git
    branch: main
    subDir: policies
    checkoutDir: /policies
    updatePollInterval: 10s
    operationTimeout: 30s
    https:
      username: ${GITHUB_USERNAME}
      password: ${GITHUB_TOKEN}
```

### Environment

```markdown
- OS: OpenShift 4.14+
- Cerbos version: 0.44.0
- Docker version: crio 1.29.13-4.rhaos4.16.git3505178.el9
- Go version: -
```

### Anything else?

checking manually on `polution` of the git working directory in the pod doesn't show anything obvious ...

```
{
  "container_path": "/policies",
  "host_path": "/var/lib/kubelet/pods/6d210c20-3188-4ce2-9757-7d7622f474e0/volumes/kubernetes.io~empty-dir/cerbos",
  "readonly": false,
  "propagation": 0,
  "selinux_relabel": true
}
[root@node01 cerbos]# cd /var/lib/kubelet/pods/6d210c20-3188-4ce2-9757-7d7622f474e0/volumes/kubernetes.io~empty-dir/cerbos
[root@node01 cerbos]# git config --global --add safe.directory '/var/lib/kubelet/pods/6d210c20-3188-4ce2-9757-7d7622f474e0/volumes/kubernetes.io~empty-dir/cerbos'
[root@node01 cerbos]# git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```
