### ISSUE TITLE
Full configuration includes password in bcrypt instead of base64

### ISSUE THREAD

**Issue by oguzhand95** [cerbos/cerbos#431]
`adminAPI` section in the full configuration example has bcrypt password as follows;

```
adminAPI:
    enabled: true
    adminCredentials: 
      username: cerbos
      passwordHash: <BCRYPT_PASSWORD>
```

If cerbos runs with the configuration, an error will be reported;
```
<TIMESTAMP> ERROR   cerbos.grpc     Failed to get admin API credentials     {"error": "failed to base64 decode admin passwordHash: illegal base64 data at input byte 0"}
```

Please see the related section: https://docs.cerbos.dev/cerbos/latest/configuration/index.html

base64 encoding the existing bcrypt password in documentation is required.
Related source: `docs/modules/configuration/pages/index.adoc`
