### ISSUE TITLE
Link compilation failures back to original source location

### ISSUE THREAD

**Issue by haines** [cerbos/cerbos#702]
If I have a policy that does not match the schema, the `cerbos compile` error is difficult to trace back to my policy file. because internally it coerces the YAML to JSON which loses line/column number information.

For example, compiling

```yaml
apiVersion: api.cerbos.dev/v1
derivedRoles:
  name: organization_assignments
  definition:
    - name: manufacturer
      parentRoles:
        - user
      condition:
        match:
          expr: hasIntersection(R.attr.organizationAssignments.manufacturer, P.attr.organizations)
```

produces

```
Load failures
policies/derived_roles/organization_assignments.yaml: failed to unmarshal JSON: proto: (line 1:51): unknown field "definition"
```

which is confusing to the user because a) they are providing YAML not JSON and b) the error is on line 4:3 not line 1:51.
