### ISSUE TITLE
[Question] can cerbos handle attribute level access?

### ISSUE THREAD

**Issue by simkimsia** [cerbos/cerbos#776]
meaniing to say i want to craft policies that say

principal A can access resource R but only attributes RA1, RA3

principal B can access resource R but only attributes RA1, RA2, RA3

given R has RA1 - RA5

**Comment by charithe** [comment]
I can think of a couple of ways to model this particular scenario. 

If you only have a handful of principals to deal with, you can create [principal policies](https://docs.cerbos.dev/cerbos/latest/policies/principal_policies.html) for each of them. In the API request, you have to send the attributes the principal is trying to access and the policy will then give you the yes/no answer.

Request:

```yaml
...
"principal": {
  "id": "principal_a",
  "roles": ["user"],
}
...
"resource": {
  "kind": "R",
  "attr": {
    "attributesToAccess": ["RA1", "RA3"]
  }
}
...
```
Principal policy:

```yaml
apiVersion: "api.cerbos.dev/v1"
principalPolicy:
  principal: principal_a
  version: "default" 
  rules:
    - resource: R 
      actions:
        - action: "*" 
          condition: 
            match:
              expr: request.resource.attr.attributesToAccess.isSubset(["RA1", "RA3"])
          effect: EFFECT_ALLOW
```


If you have a lot of principals, creating principal policies for each is not going to scale. In that case you should store the attributes that each principal has access to in a data store and send them along with the API request to Cerbos. The [resource policy](https://docs.cerbos.dev/cerbos/latest/policies/resource_policies.html) can then make a decision based on the value of that principal attribute.

Request:

```yaml
...
"principal": {
  "id": "principal_a",
  "roles": ["user"],
  "attr": {
    "allowedAttributes": ["RA1", "RA3"]
  }
}
...
"resource": {
  "kind": "R",
  "attr": {
    "attributesToAccess": ["RA1", "RA2"]
  }
}
...
```

Resource policy:

```yaml
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default" 
  resource: "R"  
  rules:
    - actions: ['*']
      effect: EFFECT_ALLOW
      roles: ["user"]
      condition:
        match:
          expr: request.resource.attr.attributesToAccess.isSubset(request.principal.attr.allowedAttributes)
```
